[find.find]
description = "Find the open tab that matches the query (searching the title, URL, and page content), and make that tab (and window) active"
match = """
  ( bring me to | go to | open | focus on | show | switch to | find ) [query] tab
  ( bring me to | go to | open | focus on | show | switch to | find |) (my)  [query] tab
"""

[[find.find.example]]
phrase = "Find calendar tab"

[[find.find.example]]
phrase = "switch to calendar "

[[find.find.example]]
phrase = "go to calendar"
test = true

[[find.find.example]]
phrase = "bring up calendar"
test = true
